export const regions = [
    { name: "Afghanistan", code: "AF", numberCode: "+93" },
    { name: "Albania", code: "AL", numberCode: "+355" },
    { name: "Algeria", code: "DZ", numberCode: "+213" },
    { name: "Andorra", code: "AD", numberCode: "+376" },
    { name: "Angola", code: "AO", numberCode: "+244" },
    { name: "Anguilla", code: "AI", numberCode: "+1-264" },
    { name: "Antarctica", code: "AQ", numberCode: "+672" },
    { name: "Antigua and Barbuda", code: "AG", numberCode: "+1-268" },
    { name: "Argentina", code: "AR", numberCode: "+54" },
    { name: "Armenia", code: "AM", numberCode: "+374" },
    { name: "Aruba", code: "AW", numberCode: "+297" },
    { name: "Australia", code: "AU", numberCode: "+61" },
    { name: "Austria", code: "AT", numberCode: "+43" },
    { name: "Azerbaijan", code: "AZ", numberCode: "+994" },
    { name: "Bahamas", code: "BS", numberCode: "+1-242" },
    { name: "Bahrain", code: "BH", numberCode: "+973" },
    { name: "Bangladesh", code: "BD", numberCode: "+880" },
    { name: "Barbados", code: "BB", numberCode: "+1-246" },
    { name: "Belarus", code: "BY", numberCode: "+375" },
    { name: "Belgium", code: "BE", numberCode: "+32" },
    { name: "Belize", code: "BZ", numberCode: "+501" },
    { name: "Benin", code: "BJ", numberCode: "+229" },
    { name: "Bermuda", code: "BM", numberCode: "+1-441" },
    { name: "Bhutan", code: "BT", numberCode: "+975" },
    { name: "Bolivia", code: "BO", numberCode: "+591" },
    { name: "Bosnia and Herzegovina", code: "BA", numberCode: "+387" },
    { name: "Botswana", code: "BW", numberCode: "+267" },
    { name: "Brazil", code: "BR", numberCode: "+55" },
    { name: "British Indian Ocean Territory", code: "IO", numberCode: "+246" },
    { name: "British Virgin Islands", code: "VG", numberCode: "+1-284" },
    { name: "Brunei", code: "BN", numberCode: "+673" },
    { name: "Bulgaria", code: "BG", numberCode: "+359" },
    { name: "Burkina Faso", code: "BF", numberCode: "+226" },
    { name: "Burundi", code: "BI", numberCode: "+257" },
    { name: "Cambodia", code: "KH", numberCode: "+855" },
    { name: "Cameroon", code: "CM", numberCode: "+237" },
    { name: "Canada", code: "CA", numberCode: "+1" },
    { name: "Cape Verde", code: "CV", numberCode: "+238" },
    { name: "Cayman Islands", code: "KY", numberCode: "+1-345" },
    { name: "Central African Republic", code: "CF", numberCode: "+236" },
    { name: "Chad", code: "TD", numberCode: "+235" },
    { name: "Chile", code: "CL", numberCode: "+56" },
    { name: "China", code: "CN", numberCode: "+86" },
    { name: "Christmas Island", code: "CX", numberCode: "+61" },
    { name: "Cocos Islands", code: "CC", numberCode: "+61" },
    { name: "Colombia", code: "CO", numberCode: "+57" },
    { name: "Comoros", code: "KM", numberCode: "+269" },
    { name: "Cook Islands", code: "CK", numberCode: "+682" },
    { name: "Costa Rica", code: "CR", numberCode: "+506" },
    { name: "Croatia", code: "HR", numberCode: "+385" },
    { name: "Cuba", code: "CU", numberCode: "+53" },
    { name: "Curacao", code: "CW", numberCode: "+599" },
    { name: "Cyprus", code: "CY", numberCode: "+357" },
    { name: "Czech Republic", code: "CZ", numberCode: "+420" },
    { name: "Democratic Republic of the Congo", code: "CD", numberCode: "+243" },
    { name: "Denmark", code: "DK", numberCode: "+45" },
    { name: "Djibouti", code: "DJ", numberCode: "+253" },
    { name: "Dominica", code: "DM", numberCode: "+1-767" },
    { name: "Dominican Republic", code: "DO", numberCode: "+1-809" },
    { name: "East Timor", code: "TL", numberCode: "+670" },
    { name: "Ecuador", code: "EC", numberCode: "+593" },
    { name: "Egypt", code: "EG", numberCode: "+20" },
    { name: "El Salvador", code: "SV", numberCode: "+503" },
    { name: "Equatorial Guinea", code: "GQ", numberCode: "+240" },
    { name: "Eritrea", code: "ER", numberCode: "+291" },
    { name: "Estonia", code: "EE", numberCode: "+372" },
    { name: "Ethiopia", code: "ET", numberCode: "+251" },
    { name: "Falkland Islands", code: "FK", numberCode: "+500" },
    { name: "Faroe Islands", code: "FO", numberCode: "+298" },
    { name: "Fiji", code: "FJ", numberCode: "+679" },
    { name: "Finland", code: "FI", numberCode: "+358" },
    { name: "France", code: "FR", numberCode: "+33" },
    { name: "French Guiana", code: "GF", numberCode: "+594" },
    { name: "French Polynesia", code: "PF", numberCode: "+689" },
    { name: "Gabon", code: "GA", numberCode: "+241" },
    { name: "Gambia", code: "GM", numberCode: "+220" },
    { name: "Georgia", code: "GE", numberCode: "+995" },
    { name: "Germany", code: "DE", numberCode: "+49" },
    { name: "Ghana", code: "GH", numberCode: "+233" },
    { name: "Gibraltar", code: "GI", numberCode: "+350" },
    { name: "Greece", code: "GR", numberCode: "+30" },
    { name: "Greenland", code: "GL", numberCode: "+299" },
    { name: "Grenada", code: "GD", numberCode: "+1-473" },
    { name: "Guadeloupe", code: "GP", numberCode: "+590" },
    { name: "Guam", code: "GU", numberCode: "+1-671" },
    { name: "Guatemala", code: "GT", numberCode: "+502" },
    { name: "Guernsey", code: "GG", numberCode: "+44-1481" },
    { name: "Guinea", code: "GN", numberCode: "+224" },
    { name: "Guinea-Bissau", code: "GW", numberCode: "+245" },
    { name: "Guyana", code: "GY", numberCode: "+592" },
    { name: "Haiti", code: "HT", numberCode: "+509" },
    { name: "Honduras", code: "HN", numberCode: "+504" },
    { name: "Hong Kong", code: "HK", numberCode: "+852" },
    { name: "Hungary", code: "HU", numberCode: "+36" },
    { name: "Iceland", code: "IS", numberCode: "+354" },
    { name: "India", code: "IN", numberCode: "+91" },
    { name: "Indonesia", code: "ID", numberCode: "+62" },
    { name: "Iran", code: "IR", numberCode: "+98" },
    { name: "Iraq", code: "IQ", numberCode: "+964" },
    { name: "Ireland", code: "IE", numberCode: "+353" },
    { name: "Isle of Man", code: "IM", numberCode: "+44-1624" },
    { name: "Israel", code: "IL", numberCode: "+972" },
    { name: "Italy", code: "IT", numberCode: "+39" },
    { name: "Ivory Coast", code: "CI", numberCode: "+225" },
    { name: "Jamaica", code: "JM", numberCode: "+1-876" },
    { name: "Japan", code: "JP", numberCode: "+81" },
    { name: "Jersey", code: "JE", numberCode: "+44-1534" },
    { name: "Jordan", code: "JO", numberCode: "+962" },
    { name: "Kazakhstan", code: "KZ", numberCode: "+7" },
    { name: "Kenya", code: "KE", numberCode: "+254" },
    { name: "Kiribati", code: "KI", numberCode: "+686" },
    { name: "Kosovo", code: "XK", numberCode: "+383" },
    { name: "Kuwait", code: "KW", numberCode: "+965" },
    { name: "Kyrgyzstan", code: "KG", numberCode: "+996" },
    { name: "Laos", code: "LA", numberCode: "+856" },
    { name: "Latvia", code: "LV", numberCode: "+371" },
    { name: "Lebanon", code: "LB", numberCode: "+961" },
    { name: "Lesotho", code: "LS", numberCode: "+266" },
    { name: "Liberia", code: "LR", numberCode: "+231" },
    { name: "Libya", code: "LY", numberCode: "+218" },
    { name: "Liechtenstein", code: "LI", numberCode: "+423" },
    { name: "Lithuania", code: "LT", numberCode: "+370" },
    { name: "Luxembourg", code: "LU", numberCode: "+352" },
    { name: "Macao", code: "MO", numberCode: "+853" },
    { name: "Macedonia", code: "MK", numberCode: "+389" },
    { name: "Madagascar", code: "MG", numberCode: "+261" },
    { name: "Malawi", code: "MW", numberCode: "+265" },
    { name: "Malaysia", code: "MY", numberCode: "+60" },
    { name: "Maldives", code: "MV", numberCode: "+960" },
    { name: "Mali", code: "ML", numberCode: "+223" },
    { name: "Malta", code: "MT", numberCode: "+356" },
    { name: "Marshall Islands", code: "MH", numberCode: "+692" },
    { name: "Martinique", code: "MQ", numberCode: "+596" },
    { name: "Mauritania", code: "MR", numberCode: "+222" },
    { name: "Mauritius", code: "MU", numberCode: "+230" },
    { name: "Mayotte", code: "YT", numberCode: "+262" },
    { name: "Mexico", code: "MX", numberCode: "+52" },
    { name: "Micronesia", code: "FM", numberCode: "+691" },
    { name: "Moldova", code: "MD", numberCode: "+373" },
    { name: "Monaco", code: "MC", numberCode: "+377" },
    { name: "Mongolia", code: "MN", numberCode: "+976" },
    { name: "Montenegro", code: "ME", numberCode: "+382" },
    { name: "Montserrat", code: "MS", numberCode: "+1-664" },
    { name: "Morocco", code: "MA", numberCode: "+212" },
    { name: "Mozambique", code: "MZ", numberCode: "+258" },
    { name: "Myanmar", code: "MM", numberCode: "+95" },
    { name: "Namibia", code: "NA", numberCode: "+264" },
    { name: "Nauru", code: "NR", numberCode: "+674" },
    { name: "Nepal", code: "NP", numberCode: "+977" },
    { name: "Netherlands", code: "NL", numberCode: "+31" },
    { name: "Netherlands Antilles", code: "AN", numberCode: "+599" },
    { name: "New Caledonia", code: "NC", numberCode: "+687" },
    { name: "New Zealand", code: "NZ", numberCode: "+64" },
    { name: "Nicaragua", code: "NI", numberCode: "+505" },
    { name: "Niger", code: "NE", numberCode: "+227" },
    { name: "Nigeria", code: "NG", numberCode: "+234" },
    { name: "Niue", code: "NU", numberCode: "+683" },
    { name: "North Korea", code: "KP", numberCode: "+850" },
    { name: "Northern Mariana Islands", code: "MP", numberCode: "+1-670" },
    { name: "Norway", code: "NO", numberCode: "+47" },
    { name: "Oman", code: "OM", numberCode: "+968" },
    { name: "Pakistan", code: "PK", numberCode: "+92" },
    { name: "Palau", code: "PW", numberCode: "+680" },
    { name: "Palestine", code: "PS", numberCode: "+970" },
    { name: "Panama", code: "PA", numberCode: "+507" },
    { name: "Papua New Guinea", code: "PG", numberCode: "+675" },
    { name: "Paraguay", code: "PY", numberCode: "+595" },
    { name: "Peru", code: "PE", numberCode: "+51" },
    { name: "Philippines", code: "PH", numberCode: "+63" },
    { name: "Pitcairn", code: "PN", numberCode: "+64" },
    { name: "Poland", code: "PL", numberCode: "+48" },
    { name: "Portugal", code: "PT", numberCode: "+351" },
    { name: "Puerto Rico", code: "PR", numberCode: "+1-787" },
    { name: "Qatar", code: "QA", numberCode: "+974" },
    { name: "Republic of the Congo", code: "CG", numberCode: "+242" },
    { name: "Reunion", code: "RE", numberCode: "+262" },
    { name: "Romania", code: "RO", numberCode: "+40" },
    { name: "Russia", code: "RU", numberCode: "+7" },
    { name: "Rwanda", code: "RW", numberCode: "+250" },
    { name: "Saint Barthelemy", code: "BL", numberCode: "+590" },
    { name: "Saint Helena", code: "SH", numberCode: "+290" },
    { name: "Saint Kitts and Nevis", code: "KN", numberCode: "+1-869" },
    { name: "Saint Lucia", code: "LC", numberCode: "+1-758" },
    { name: "Saint Martin", code: "MF", numberCode: "+590" },
    { name: "Saint Pierre and Miquelon", code: "PM", numberCode: "+508" },
    { name: "Saint Vincent and the Grenadines", code: "VC", numberCode: "+1-784" },
    { name: "Samoa", code: "WS", numberCode: "+685" },
    { name: "San Marino", code: "SM", numberCode: "+378" },
    { name: "Sao Tome and Principe", code: "ST", numberCode: "+239" },
    { name: "Saudi Arabia", code: "SA", numberCode: "+966" },
    { name: "Senegal", code: "SN", numberCode: "+221" },
    { name: "Serbia", code: "RS", numberCode: "+381" },
    { name: "Seychelles", code: "SC", numberCode: "+248" },
    { name: "Sierra Leone", code: "SL", numberCode: "+232" },
    { name: "Singapore", code: "SG", numberCode: "+65" },
    { name: "Sint Maarten", code: "SX", numberCode: "+1-721" },
    { name: "Slovakia", code: "SK", numberCode: "+421" },
    { name: "Slovenia", code: "SI", numberCode: "+386" },
    { name: "Solomon Islands", code: "SB", numberCode: "+677" },
    { name: "Somalia", code: "SO", numberCode: "+252" },
    { name: "South Africa", code: "ZA", numberCode: "+27" },
    { name: "South Korea", code: "KR", numberCode: "+82" },
    { name: "South Sudan", code: "SS", numberCode: "+211" },
    { name: "Spain", code: "ES", numberCode: "+34" },
    { name: "Sri Lanka", code: "LK", numberCode: "+94" },
    { name: "Sudan", code: "SD", numberCode: "+249" },
    { name: "Suriname", code: "SR", numberCode: "+597" },
    { name: "Svalbard and Jan Mayen", code: "SJ", numberCode: "+47" },
    { name: "Swaziland", code: "SZ", numberCode: "+268" },
    { name: "Sweden", code: "SE", numberCode: "+46" },
    { name: "Switzerland", code: "CH", numberCode: "+41" },
    { name: "Syria", code: "SY", numberCode: "+963" },
    { name: "Taiwan", code: "TW", numberCode: "+886" },
    { name: "Tajikistan", code: "TJ", numberCode: "+992" },
    { name: "Tanzania", code: "TZ", numberCode: "+255" },
    { name: "Thailand", code: "TH", numberCode: "+66" },
    { name: "Togo", code: "TG", numberCode: "+228" },
    { name: "Tokelau", code: "TK", numberCode: "+690" },
    { name: "Tonga", code: "TO", numberCode: "+676" },
    { name: "Trinidad and Tobago", code: "TT", numberCode: "+1-868" },
    { name: "Tunisia", code: "TN", numberCode: "+216" },
    { name: "Turkey", code: "TR", numberCode: "+90" },
    { name: "Turkmenistan", code: "TM", numberCode: "+993" },
    { name: "Turks and Caicos Islands", code: "TC", numberCode: "+1-649" },
    { name: "Tuvalu", code: "TV", numberCode: "+688" },
    { name: "U.S. Virgin Islands", code: "VI", numberCode: "+1-340" },
    { name: "Uganda", code: "UG", numberCode: "+256" },
    { name: "Ukraine", code: "UA", numberCode: "+380" },
    { name: "United Arab Emirates", code: "AE", numberCode: "+971" },
    { name: "United Kingdom", code: "GB", numberCode: "+44" },
    { name: "United States", code: "US", numberCode: "+1" },
    { name: "Uruguay", code: "UY", numberCode: "+598" },
    { name: "Uzbekistan", code: "UZ", numberCode: "+998" },
    { name: "Vanuatu", code: "VU", numberCode: "+678" },
    { name: "Vatican", code: "VA", numberCode: "+379" },
    { name: "Venezuela", code: "VE", numberCode: "+58" },
    { name: "Vietnam", code: "VN", numberCode: "+84" },
    { name: "Wallis and Futuna", code: "WF", numberCode: "+681" },
    { name: "Western Sahara", code: "EH", numberCode: "+212" },
    { name: "Yemen", code: "YE", numberCode: "+967" },
    { name: "Zambia", code: "ZM", numberCode: "+260" },
    { name: "Zimbabwe", code: "ZW", numberCode: "+263" }
];
